global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'tms-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/metrics'
    
  - job_name: 'tms-frontend'
    static_configs:
      - targets: ['frontend:80']
