name: aplikasi_tms
description: "Transport Management System (TMS) Flutter frontend application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  file_picker: ^5.2.5
  image_picker: ^0.8.7
  connectivity_plus: ^3.0.3
  sqflite: ^2.2.6
  cached_network_image: ^3.2.3
  image: ^4.0.15
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true