name: Docker Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: |
        cp .env.example .env

    - name: Build and Test with Docker Compose
      run: |
        docker compose build
        docker compose up -d
        sleep 30
        docker compose exec -T backend wget --spider http://localhost:8080/health
        docker compose exec -T frontend wget --spider http://localhost:3000
        docker compose down

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Backend Image
      run: |
        docker build -t tms-backend:latest ./backend

    - name: Build Frontend Image  
      run: |
        docker build -t tms-frontend:latest ./frontend/aplikasi_tms